### ISSUE TITLE
Duplicated nodes appearing in hosts file

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#127]
When adding a new genders group that includes additional existing groups the entries in `/etc/hosts` fail to line up with the node configuration, take the following example (use case A & B from @ste78 doc *Metalware Domain Topologies - Functionality test use cases*):

```
metal configure group nodes
// node0[1-4] nodes,cluster,all  primary network 10.10.100 //

metal configure group newnodes
// newnode0[1-2] newnodes,nodes,cluster,all primary network 10.10.101 //
```

This will generate `/etc/hosts` like below (snipped to primary interface only to save space):

```
10.10.101.1 newnode01.pri.alcescluster.compute.estate newnode01.pri newnode01

10.10.101.2 newnode02.pri.alcescluster.compute.estate newnode02.pri newnode02

10.10.100.3 node01.pri.alcescluster.compute.estate node01.pri node01

10.10.100.4 node02.pri.alcescluster.compute.estate node02.pri node02

10.10.100.5 node03.pri.alcescluster.compute.estate node03.pri node03

10.10.100.6 node04.pri.alcescluster.compute.estate node04.pri node04

10.10.101.1 newnode01.pri.alcescluster.compute.estate newnode01.pri newnode01

10.10.101.2 newnode02.pri.alcescluster.compute.estate newnode02.pri newnode02
```

This incorrectly indexes the IP addresses for `node0[1-4]` and adds multiple entires for `newnode0[1-2]`.

**Comment by bobwhitelock** [comment]
Hi @ColonelPanicks - the issue here is that we just use `nodeattr -c $GROUP` for each primary group to find the nodes in that group, however this will also include nodes in the group which have a different primary group. These nodes will then be included multiple times when iterating through all nodes in all primary groups, for both their primary group and any other groups they are part of which are also primary groups, as seen here.

A possible fix to this, which would still support the above use case, would be whenever we want to get just the nodes with a particular primary group we generate a temporary genders file from the main genders file; each line in this file would only contain a single group, the primary/first one. We can then still use `nodeattr -c $GROUP` to parse the nodes in each primary group, without other nodes in that group included.

What do you and @ste78 think about doing this? There may be a better solution but depending on how you think things should work and what use cases we want to support.

**Comment by WilliamMcCumstie** [comment]
From discussing with @ColonelPanicks, there maybe a slightly easier way to fix the problem. It is based on your idea, but instead of getting `nodeattr` to filter the list, this can be done in ruby. I feel regenerating the genders file is needlessly complex.

An easier way would be to filter inside of ruby. The logic place I see is inside of `Node` class when we call `index`. Something along these lines should insure the index always refers to the `primary group index` regardless of which command calls it. 
```
def index
  if primary_group
    list_with_non_primary_nodes = Nodes.create(metalware_config, primary_group, true)
    list_with_non_primary_nodes.delete(list_of_primary_nodes_from_answer_file.to_sym).index(self)
  else
    0
  end
end
```
NOTE: `delete` returns the list of deleted keys, which is exactly what we want in this case.

Now that we have insured the `index` is correct, is is simply a case of adjusting the rendering of the `/etc/hosts` template so that it skips duplicates (I believe `array.uniq` could come in handy here).

**Comment by ColonelPanicks** [comment]
From looking at `hosts/default` in `metalware-default` it looks like the reason for duplicates is that it loops through the groups (`alces.groups`) and all nodes in them. This could be fixed by looping through `alces.genders.domain` group instead as that should contain all nodes. This would require that every primary group created has the additional group `domain`, so should/could that be enforced?

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie: I considered how we could remove the duplicates in Ruby, however the issue with this approach rather than delegating this to `nodeattr` is that any bug in our Ruby logic means we would then get incorrect or have missing nodes in our primary group.

Additionally, as you describe, this only corrects bad indexes, and then you would still need to adjust the `hosts` template to skip duplicates; this in itself would not be desirable as we want to make templates easy for people to work with, and having to manually handle nodes which shouldn't be there in your templates would be confusing.

This approach is trying to patch the symptoms, however the underlying issue is that when we're getting a list of nodes in a primary group we're including nodes which don't actually have that group as their own primary group. We should try to correct this rather than working around it.

@ColonelPanicks: This would fix there being duplicates, however the issue you show above where hosts in the `nodes` group have the wrong `alces.index` would remain I believe, as when we get the list of nodes in the `nodes` group the `newnode0X` nodes would still appear first.

Having investigated the options provided by `nodeattr` however I think we can possibly correct this an easier way than I suggest above. `nodeattr --expand` produces output like this:

```
[root@controller(dev) metalware]# nodeattr --expand
newnode01 newnodes,nodes,cluster,all
newnode02 newnodes,nodes,cluster,all
node01    nodes,cluster,all
node02    nodes,cluster,all
node03    nodes,cluster,all
node04    nodes,cluster,all
```

This effectively gives us a one-to-one mapping between nodes (the first column) and their corresponding primary group (the first item in the second column split along commas). We can then easily use this to get the nodes in a primary group as well as the index within their primary group of each node.

We may still want to keep the code to get _all_ nodes in a group we have currently in certain places, such as when building a group we may still will want to include all nodes in that group, whether it is their primary group or not.

**Comment by WilliamMcCumstie** [comment]
Using `--expand` looks to be a good way of determining the primary group for a node. As you mentioned, their maybe cases when we want to get all the nodes for a particular group. I think part of our problem is that we loosely use the term `group` to refer to two related by distinctly different things: (`primary group` and `gender group`).

It may be advisable that we split the two terms in the `MagicNamespace`. Maybe use `primary` when we want to iterate over nodes just in the primary group and `gender` when we want to iterate over all the nodes?

I can't think of an easier way to maintain both use cases. But open to suggestions.

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie: I'm not sure if we want to provide access to all nodes in a gender group at all when templating, but we can check with @ste78.

Currently when templating you can access `alces.groups`, which actually iterates through primary groups and may be better called something related to that, as well as `alces.genders`, which just gives the node names in a group and is not actually used anywhere, it was just added for an initial requirement we had - it may be worth removing this if we don't actually need it, or make it more consistent with `alces.groups`.

Other than that we do currently support getting all nodes in a group when running `hosts` and `build` etc for a group, so we would need to at least continue supporting this for this case.

**Comment by WilliamMcCumstie** [comment]
Well in that case, we can limit `alces.group` to be just the nodes in the primary group (renaming it might also be a good idea). Also `alces.genders` should either: 1) be modified to be more consistent with `group`, 2) be removed (as it isn't being used).

Otherwise, `build` and `hosts` iterate through the nodes directly without going through the `MagicNamespace`. Thus they should remain unaffected by the change.
