### ISSUE TITLE
View-Config Include-Groups Undefined Variable

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#136]
**Problem**

Running `view-config` with the `-i` argument doesn't see defined parameters.

```
[root@deploy_test ~]# metal view-config -i nodes
error: Unset template parameter: pri_network_defined. Use --trace to view backtrace
```

Full trace output

```
[root@deploy_test ~]# metal view-config -i nodes --trace
/opt/metalware/src/templating/missing_parameter_wrapper.rb:36:in `method_missing': Unset template parameter: pri_network_defined (Metalware::MissingParameterError)
	from (erb):1:in `block in replace_erb'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:32:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:12:in `replace_erb'
	from /opt/metalware/src/templating/repo_config_parser.rb:120:in `parse_string_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:108:in `parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:111:in `block in parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:110:in `each'
	from /opt/metalware/src/templating/repo_config_parser.rb:110:in `map'
	from /opt/metalware/src/templating/repo_config_parser.rb:110:in `parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:111:in `block in parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:110:in `each'
	from /opt/metalware/src/templating/repo_config_parser.rb:110:in `map'
	from /opt/metalware/src/templating/repo_config_parser.rb:110:in `parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:101:in `block in perform_config_parsing_pass'
	from /opt/metalware/src/templating/repo_config_parser.rb:100:in `each'
	from /opt/metalware/src/templating/repo_config_parser.rb:100:in `map'
	from /opt/metalware/src/templating/repo_config_parser.rb:100:in `perform_config_parsing_pass'
	from /opt/metalware/src/templating/repo_config_parser.rb:45:in `parse'
	from /opt/metalware/src/templating/repo_config_parser.rb:25:in `parse_for_node'
	from /opt/metalware/src/commands/view_config.rb:23:in `templating_config_json'
	from /opt/metalware/src/commands/view_config.rb:15:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:37:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

**Steps Taken**

- Installed metalware `develop` branch

- Used the `metalware-default` repo for config templates

- Ran through `metal configure domain`

- Ran through `metal configure group nodes`

**Comment by bobwhitelock** [comment]
Thanks for the thorough issue @ColonelPanicks :slightly_smiling_face:. So there's really 2 parts to the issue here:

- firstly, we weren't giving an informative error message when you attempt to `view-config` for a node which doesn't exist - I've fixed this in the PR above;

- secondly, and probably the reason you thought this was an issue with the `-i` option, is that it may not be as clear as it could be what this option is doing. I'll try to describe this more below.

When Metalware is templating, there's essentially 2 ways this can happen:

- we can either be rendering templates for a particular node, in which case various node-specific templating parameters will be set, e.g. `alces.nodename` and `alces.group_index`, as well as any user-defined template parameters in configs more specific than the `domain.yaml` config;

- or we can be rendering templates for no particular node - this just means that less parameters will be set, e.g. `alces.nodename` and `alces.group_index` are `nil`, and only the `domain.yaml` config is loaded. We tend to do things this way when rendering templates which aren't for a particular node, e.g. `dhcp` or `hosts`, as it doesn't make sense to pass any particular node in. However the domain-related parameters we use when rendering these templates, e.g. `alces.groups`, are still accessible when we are rendering a template for a particular node.

The `view-config` command is basically supposed to be a way to view the standard templating config which will be used as accurately as possible, so all passing a node name in does is switch between these two versions  of templating.

The `-i` option serves an orthogonal purpose: it is a special case to tell `view-config` to include all the `alces.groups` namespaces, and `nodes` within these groups, when showing the config. The reason I added this is because the `groups` namespace is by far the largest part of the config, so including this by default makes the output a lot longer and harder to find what you're interested in if you don't care about the groups; it also slows things down quite a bit to load the config for every node in every group (this isn't an issue normally apart for templates where you need them, as they're only loaded as needed).

This is essentially a roundabout way of saying that when you run `metal view-config -i nodes` you're telling Metalware to show you the config when rendering templates in the context of a node called `nodes`, and to also include the configs for every node in every group under `alces.groups` because you're interested in this. The uninformative error message here doesn't help make things clearer.

The above is also the main reason I added the `view-answers` command, to be useful at the other end of the spectrum between showing what Metalware is using as its config behind the scenes and showing what answers have been configured.

Apologies for the long explanation, but hopefully it's somewhat informative. As our resident docs expert do you think there's any ways we could make any of this a bit clearer in the docs? We have some templating docs [here](https://github.com/alces-software/metalware/blob/develop/docs/templating-system.md), or the source for the `view-config` help is [here](https://github.com/alces-software/metalware/blob/develop/src/cli_helper/config.yaml#L339,L352). Any PRs or suggestions via issues or Slack would be much appreciated; it can be hard to tell how clear things are when I know exactly what the code underneath is doing :slightly_smiling_face:.

**Comment by ColonelPanicks** [comment]
@bobwhitelock thank you for the thorough explanation! That makes a lot more sense now. I'll happily take a look at the docs that are currently in place and see what improvements can be made. I've also had a play with `view-answers` so happy with how that works too!

**Comment by bobwhitelock** [comment]
Great, thanks @ColonelPanicks! :slightly_smiling_face:
