### ISSUE TITLE
Cannot configure domain unless an eth0 interface is present

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#202]
Even if `build_interface:` is set to `em1` in `server.yaml` the following error is seen when running configure domain:
```
Aborting rendering domain templates; the rendered server config is invalid:
>>> em1 is not a valid interface; valid interfaces: lo, eth0, eth1, eth2
error: An error occurred rendering: metalware_server_config. Use --trace to view backtrace
```

Trace output:
```
coming soon
```

Notes from discussion
> "I was right all along, it was fucked. Apology retracted" - @ste78

**Comment by ColonelPanicks** [comment]
### Fresh install on system with em* interfaces

The following error occurs at the end of first domain configure
```
# Error
error: '/opt/metalware/libexec/determine-hostip eth0' produced error 'Device "eth0" does not exist.'. Use --trace to view backtrace

# Trace
/opt/metalware/src/system_command.rb:70:in `handle_error': '/opt/metalware/libexec/determine-hostip eth0' produced error 'Device "eth0" does not exist.' (Metalware::SystemCommandError)
	from /opt/metalware/src/system_command.rb:41:in `run'
	from /opt/metalware/src/deployment_server.rb:75:in `ip_on_interface'
	from /opt/metalware/src/deployment_server.rb:29:in `ip'
	from /opt/metalware/src/templating/magic_namespace.rb:108:in `hostip'
	from /opt/metalware/src/templating/missing_parameter_wrapper.rb:34:in `method_missing'
	from /opt/metalware/src/templating/missing_parameter_wrapper.rb:34:in `method_missing'
	from (erb):1:in `wrapper_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:56:in `render_erb_template'
	from /opt/metalware/src/templating/renderer.rb:34:in `replace_erb'
	from /opt/metalware/src/templating/repo_config_parser.rb:132:in `parse_string_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:120:in `parse_config_value'
	from /opt/metalware/src/templating/repo_config_parser.rb:113:in `block in perform_config_parsing_pass'
	from /opt/metalware/src/templating/repo_config_parser.rb:112:in `each'
	from /opt/metalware/src/templating/repo_config_parser.rb:112:in `map'
	from /opt/metalware/src/templating/repo_config_parser.rb:112:in `perform_config_parsing_pass'
	from /opt/metalware/src/templating/repo_config_parser.rb:56:in `parse'
	from /opt/metalware/src/templating/repo_config_parser.rb:36:in `parse_for_node'
	from /opt/metalware/src/templater.rb:161:in `initialize'
	from /opt/metalware/src/templater.rb:63:in `new'
	from /opt/metalware/src/templater.rb:63:in `render'
	from /opt/metalware/src/templater.rb:78:in `render_to_file'
	from /opt/metalware/src/domain_templates_renderer.rb:160:in `render_fully_managed_template'
	from /opt/metalware/src/domain_templates_renderer.rb:66:in `render_metalware_server_config'
	from /opt/metalware/src/domain_templates_renderer.rb:43:in `block in render'
	from /opt/metalware/src/domain_templates_renderer.rb:42:in `each'
	from /opt/metalware/src/domain_templates_renderer.rb:42:in `render'
	from /opt/metalware/src/command_helpers/configure_command.rb:93:in `render_domain_templates'
	from /opt/metalware/src/command_helpers/configure_command.rb:45:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:40:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

_Note: `server.yaml` has `em1` set as the build interface by default_

This issue can be worked around by replacing `eth0` with `em1` in https://github.com/alces-software/metalware/blob/develop/src/deployment_server.rb#L59

**Comment by bobwhitelock** [comment]
The `build_interface` should be an interface which exists on _the machine Metalware is running on_, as it is used to determine what the Metalware server's IP is on this interface  (i.e. `alces.hostip`). This IP is then used to form the URLs etc that other machines being built should make requests to.

The `build_interface` comes from the rendered `server.yaml`, which is the first thing rendered at the end of every `configure` command. When rendering `server.yaml`, if the value for `build_interface` is not the name of an existing interface (as can be seen by running `ip addr`), then you'll get an error like in your initial comment. In this case, `build_interface` has been set to `em1`, but the valid interfaces on the Metalware server are `lo, eth0, eth1, eth2`. We fail fast and do not save the rendered `server.yaml` to avoid saving an interface which doesn't exist as the build interface.

If we did save an interface which doesn't exist as the `build_interface`, then we wouldn't be able to determine the IP of the Metalware server on this interface, as the interface doesn't exist. This explains the error in the second comment: prior to a rendered `server.yaml` existing (_which includes the first time the `server.yaml` is rendered, such as in the first `configure domain` after a fresh install_) a default interface name is used. Previously this default was `eth0`, as I assumed every machine has an `eth0` interface, however this was an incorrect assumption. With the change in https://github.com/alces-software/metalware/pull/213 this should now be fixed to use the first valid interface, which by definition should always be a valid interface.

Note: since we don't actually use the value for `alces.hostip` when determining the `build_interface`, it doesn't actually matter which interface the first interface happens to be. It should just be a valid interface so the `determine-hostip` script doesn't blow up.

Hopefully this clears things up and explains how `server.yaml` and `build_interface` work, and what those error messages meant. If not I'd be happy to explain in person, it may be clearer what's going on with a diagram as it can be a bit tricky to get your head around (it was for me after coming back to this after a while :slightly_smiling_face:). Let me know if this would be useful.
