### ISSUE TITLE
[feature/alces-self] Config references not resolving `alces.answers`

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#214]
The named reverse zone name is determined in `config/domain.yaml` with:
```
named_rev_zone: <% split_net = networks.pri.network.split(/\./) -%><%= split_net[1] %>.<%= split_net[0] %>
```
This no longer resolves to `10.10` (in the case of primary network) and is resolved as `answers. alces`. An extract from render of a file containing `<%= networks.inspect %>` is below for clarity:
```
[root@controller repo]# metal render /tmp/test node01
#<Metalware::Templating::IterableRecursiveOpenStruct pri={:defined=>true, :interface=>"eth0", :hostname=>"node01.pri.testcluster.cluster.local", :domain=>"pri", :short_hostname=>"node01.pri", :ip=>"10.10.1.1", :netmask=>"255.255.0.0", :network=>"10.10.0.0", :gateway=>nil, :type=>nil, :primary=>true, :named_fwd_zone=>"pri.testcluster.cluster.local", :named_rev_zone=>"answers. alces", :firewallpolicy=>"internal"}
```

**Comment by WilliamMcCumstie** [comment]
As discussed with @ColonelPanicks irl,

There is a race condition between the answers with the string processing (`split(/\./)`). When rendering a dummy template, `/tmp/template`:
```
<%= split_net = networks.pri.network.split(/\./) %>
```
The output is:
```
[root@localhost metalware]# bin/metal render /tmp/template
warning: Unset template parameter: alces.answers.pri_network_defined
warning: Unset template parameter: alces.answers.mgt_network_defined
warning: Unset template parameter: alces.answers.ib_network_defined
warning: Unset template parameter: alces.answers.bmc_network_defined
["10", "10", "0", "0"]
```
So the `networks.pri.network.split(/\./)` returns the correct value at least some of the time.

So appears that when `named_rev_zone` sometimes receives the unrendered version of `networks.pri.network` (which contains `alces.answers...`). This would normally be fine as the unrendered ERB would be replaced on the next iteration. The string processing kicks in and causes the malformed ERB tag.

The fix is to never return a value from a `Namespace` without rendering first. However as their is a significant amount of work evolved in this, it will not be ready for the `2017.1.0` release.

Instead the fix to make `named` work is to not embeded the call to `alces.answers` within another config parameter. Config values that require string processing must not call other config values with embedded ERB as the iterator can not be guaranteed to replace it.

**Comment by WilliamMcCumstie** [comment]
For more details on the fix, refer to: https://github.com/alces-software/metalware-default/commit/5b38b2d7e42347663c82f8e21c8f6afdeb91d6de

**Comment by WilliamMcCumstie** [comment]
From now on, configs and answers are recursively rendered on demand. This means a value should never be returned containing ERB. This removes the race condition when doing string processing.

See #223 for more details on how the namespaces used and how configs are rendered.
