### ISSUE TITLE
[Plugins] Ordering of Plugin Execution

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#302]
There is still requirement to control the execution order of the plugins. This used to be accomplished (pre-plugins) by numbering the scripts such that the `files.setup` namespace would execute alphanumerically but this would neither be a clean nor flexible way of ensuring plugins run in a specific order. 

An example of the ordering of plugins from a system running `2018.1.0-rc1`:
* infiniband
* ganglia
* slurm
* ipa
* flightdirect
* flightcenter
* yumrepo

Ideally, on top of the activate/deactivate functionality, the option to add priority or order information to a plugin would be part of the metal plugin commands.

**Comment by bobwhitelock** [comment]
> This used to be accomplished (pre-plugins) by numbering the scripts such that the files.setup namespace would execute alphanumerically but this would neither be a clean nor flexible way of ensuring plugins run in a specific order.

I believe this used to work - however with the recent switch to the new templating namespaces as far as I can see this no longer should work. The function which used to do this still exists, but is no longer used anywhere AFAICS: https://github.com/alces-software/metalware/blob/ebe37c359646691d0ecc04a8833e1587f87be137/src/hash_mergers/hash_merger.rb#L92-L96

Have you confirmed whether this still works this way recently?

It's also possible that this change was a deliberate decision, as now files should appear within the namespace in the order they were defined, rather than alphabetically. This may make also sense with the other recent change that file namespaces now replace each other rather than are merged, so there wouldn't be much advantage to having the files be available in alphabetical order since they could just be placed in the order they should be available anyway.

In any case, I don't think this would help work around this issue whichever way the plugin files are ordered within the files namespace. Currently we run the files like this: https://github.com/alces-software/metalware-default/blob/develop/files/main.sh#L49,L59

so every `infiniband` file in `files.setup` would already have executed before any of the `ganglia` files in `files.setup` would start being fetched and executed.

However, if the priorities different scripts should run in are fairly standard across clusters and nodes (i.e. there aren't any/many scripts like `foo.sh` and `bar.sh` where in some cases `foo.sh` must run first and in others `bar.sh` must run first), then a simple way to support this within the current way Metalware works would be to add more file namespaces which we attempt to run within the `main.sh` script. There would need to be as many of these as we want discrete priority levels for plugin files. Then every file in a later level could assume all scripts at an earlier level (and so higher priority) had already run.

An alternative, possibly more flexible, approach to achieve a similar result would be to add a `priority` flag to each plugin config. This could then be used when running all plugin files to run these in the order of the plugin's priority for the current node. This would have the advantage of allowing the plugin's priority to vary between nodes or based on a `configure` answer etc. This would also mean we'd need (possibly a lot) less possible `files` sections available for all plugins. It would mean we have a bit more Ruby embedded in the `main.sh` template. I can explain more/have a go at doing this approach if it sounds like it would solve you problems at the moment.

If neither of these approaches would work for some reason then we may need to consider incorporating something specifically to handle this in Metalware.

**Comment by ColonelPanicks** [comment]
The issue isn't the alphanumeric numbering of scripts within the files namespace isn't working but the fact that the lists are now separate for plugins as each list is within `node.plugins.plugin_name.files` so therefore it doesn't order based on the _other_ plugin files. 

I think the option of more files namespaces would begin to feel clunky, with namespaces being created for one plugin or script (as we don't have discrete control over ordering within that namespace). At the moment, the namespaces are fairly logical:
- Platform (any cloud or metal-specific configuration)
- Setup (scripts to run before the core script)
- Core (network, mail, logging, ntp)
- Scripts (any other scripts to run)

There are a couple of plugins that should run before the core scripts but making additional namespaces (`setup1`, `setup2`) would feel convoluted.

Personally, I really like the idea of adding a priority to the plugins themselves. How would you propose this would work?

**Comment by bobwhitelock** [comment]
> The issue isn't the alphanumeric numbering of scripts within the files namespace isn't working but the fact that the lists are now separate for plugins as each list is within node.plugins.plugin_name.files so therefore it doesn't order based on the other plugin files.

Possibly I'm mistaken/misunderstanding but I think it's both - all files for each plugin are currently run in turn before moving on to the next plugin, but even if all plugin files were run in one loop they still wouldn't be ordered as you might expect (although this would still be possible with just some changes to the repo I believe).

> I think the option of more files namespaces would begin to feel clunky

This is a good point, I think I agree

> Personally, I really like the idea of adding a priority to the plugins themselves. How would you propose this would work?

Let me have an experiment and I'll try and send you a `metalware-default` branch to do this if I can get something working :slightly_smiling_face:.

**Comment by bobwhitelock** [comment]
@ColonelPanicks give the above repo branch a try when you get a chance. It should allow you to do what I described above with a `priority` config value for plugins. Let me know if anything's unclear or doesn't work :slightly_smiling_face:.

**Comment by ColonelPanicks** [comment]
Brilliant, those changes work as expected! Thanks for looking into that @bob, it's a nice lil fix.
