### ISSUE TITLE
Change of method for passing IPMI command to be used in `metal ipmi` 

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/metalware#348]
Originally the `alces ipmi` and `metal ipmi` tools used `-c` to pass the command to be used in the underlying `ipmitool`. This was (from what I can see..) to emulate the behaviour of `ipmitool` which takes `-c` for the command to be sent to either the local IPMI device or a remote IPMI interface (when using `-H` to `ipmitool`.

This has changed to `-k` and most recently nothing supplied for the command. Not having to remember which version of `metal ipmi` or `alces ipmi` is being used for a particular cluster would be good as I can now think of 5 or 6 different ways of performing the same action throughout the different generations of cluster.

**Comment by WilliamMcCumstie** [comment]
I agree that `ipmi` has been rather volatile in its conversion from a bash to ruby. The `cli` file has been updated to include all the legacy tags `-c`, `-k` and `--command`. None of these flags are required and are otherwise ignored by metalware.

Their inclusion into the `cli` should allow backwards compatibility (mostly) with old metalware versions. The only requirement is that the `node/group` must come first as the flag does not tell metalware that the inputs have switched order.
