### ISSUE TITLE
Various help commands do not work as described

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/metalware#40]
According to `metal --help`:
```
For more help on a particular command run:
  metal COMMAND help
```

However this does not work for many commands:

```
[root@controller(bobdomain) cli]# metal boot help
(CTRL+C TO TERMINATE)
Exiting....Done
ERROR: Requires a node name, node group, or json input
```

```
[root@controller(bobdomain) cli]# metal console help
Attempting to establish SOL session on help..^CFAILED!
Establishing SOL connection, type &. to exit..
^C
SIGN INT: Close Interface IPMI v2.0 RMCP+ LAN Interface
FAILED!
```

```
[root@controller(bobdomain) cli]# metal each help
Gender group is required, -g <gender>
```

```
[root@controller(bobdomain) cli]# metal hosts help
ERROR: Requires a node name, node group, or json
```

```
[root@controller(bobdomain) cli]# metal hunter help
WAITING FOR NEW NODES TO APPEAR ON THE NETWORK, PLEASE NETWORK BOOT THEM NOW... (CTRL+C TO TERMINATE)
setfilter: syntax error
```

In none of these cases does `metal help $COMMAND` work either.

In the case of `console`, `metal console --help` does not work either, meaning it is not possible to see from the command line what arguments (if any) this command takes.

Also odd:

```
[root@controller(bobdomain) cli]# metal help console
Attempting to establish SOL session on help..^CFAILED!
Establishing SOL connection, type &. to exit..
^C
SIGN INT: Close Interface IPMI v2.0 RMCP+ LAN Interface
FAILED!
```
but:
```
[root@controller(bobdomain) cli]# metal foo console
metal: 'foo' is not a known command. See 'metal --help'.
```

(`help` appears to be passed as an argument to console, but this is not the case for other unknown commands).

**Comment by WilliamMcCumstie** [comment]
Ok from the looks of it, the `help` option needs to be changed to `metal COMMAND --help` and that should fix most of these issues.

`Power` looks to be the only command that accepts both `help` and `--help`. This will need to be looked at so it's consistent with the others. Will also need to look into what happens if `metal COMMAND` is ran. Sometimes it returns an error and other times the help.

Will look into `console`

**Comment by BobWhitelock** [comment]
Great, that all sounds good; whatever we do it would seem best to be consistent with the commands since we're wrapping them up in one tool.

Only thing that I think is affecting what I'm doing at the moment is related to `console`, since I can't see help for it - is there anything else to know about it apart from that `metal console $NODE` attempts to open a console on `$NODE`?

**Comment by WilliamMcCumstie** [comment]
So it seems that `metal console` doesn't work with `-h`, `--help` or `help`. @mjtko will have a better idea how it works.

I will be going through and documenting how `metalware` works as well as a bit of refactoring to make the commands a bit more consistent in how they work

**Comment by BobWhitelock** [comment]
This is mostly irrelevant as we're now working on Metalware 2.0; leaving this open however to remind us to check this works well in that.

**Comment by WilliamMcCumstie** [comment]
Closing this issue as all the commands have now been ported into `2.0.0` and have corresponding help. The help for the bash commands could be improved but this could be done when they are formally integrated into `ruby`.
