### ISSUE TITLE
Weird Control Characters in PXE Config File Names

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#437]
Soooooo when the `metal build` command runs for a node it outputs the hexadecimal IP of the node but seems to be appending a strange character:
```
# ls output
[root@controller [testcluster] pxelinux.cfg]# ls
0A0A0101?  0A0A0102?  0A0A1001?  default

# Different output on tab complete
[root@controller [testcluster] pxelinux.cfg]# metal render /tmp/test node001 > /var/lib/tftpboot/pxelinux.cfg/
0A0A0101^J  0A0A0102^J  0A0A1001^J  default
```

Any idea what's going on here?? I can't read the files due to the strange control characters and PXE booting is pretty integral to metalware!

**Comment by ColonelPanicks** [comment]
This seems to be as a result of switching from `render_to_file` to `render`:
- [Change of render usage for kickstart pxe output](https://github.com/alces-software/metalware/commit/34a37e5e25cdbd19594db5397f5bdf39fae03ba0#diff-f7bb73f889f084a5380d1003c66873ff)
- [Removing of render_to_file](https://github.com/alces-software/metalware/commit/015caa47988a8fdd62d3428fd4ac2ff362200074#diff-10897e630d3610e445853b8eebbad7f6)
- [Tweaks to file write with Travis](https://github.com/alces-software/metalware/commit/dc529df0daaf8ac3ce8f238b9893149774c0c100)

All that's missing is a `chomp` in the `render` method.

**Comment by bobwhitelock** [comment]
Are you fixing this @ColonelPanicks or does it need more investigation?

**Comment by WilliamMcCumstie** [comment]
The bug is being caused by the `SystemCommand` class not `chomp`ing the new line characters off. This means `node.hexadecimal_ip`  returns the IP with the newline.

This was previously not an issue as the `Templater` was previously removing it in its file writing method, however this has since been removed.

An ease fix would be to add the `chomp` back when writing the file. However the more logical fix would be remove the endline from the hexip in the first place.

Either way this isn't a pressing issue and can be fixed before the next release. The bug does not appear in the previous releases.
