### ISSUE TITLE
Switch config used by test

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/metalware#56]
As discussed in #55 we need to switch the test over to using their own config file as opposed to the default. This is not currently causing an issue by may do in the future.

Relevant excerpt from @BobWhitelock comment: 

"
ensure the test config is used in the different tests - I think this will be the case already for most of them, but you may need to just add a `SpecUtils.use_unit_test_config(self)` to some of the existing command specs if they don't have this already (until now when testing some commands we won't have needed anything from the config file).
"

**Comment by bobwhitelock** [comment]
Rather than ensuring we always use a unit test config with mocked paths, I think the better approach will be to move towards using `FakeFS` for all tests which rely on particular file paths; this will make our tests more robust/realistic and avoid the unnecessary faking.

We are already in the process of doing this and have some related cards: https://trello.com/c/qWWyVUAX/44-address-metalware-file-testing-issues-more-robustly-consistently and https://trello.com/c/kDfpiiea/101-unify-constants-and-config-classes, so I don't think we need to keep this open.
