### ISSUE TITLE
Running metal dhcp without a template throws error

### ISSUE THREAD

**Issue by ste78** [alces-software/metalware#89]
Running `metal dhcp` without specifying a template throws an error (shouldn't it pick up the default?)

```
[root@master ~]# metal dhcp
error: no implicit conversion of nil into String. Use --trace to view backtrace
[root@master ~]# metal dhcp -t default
warning: Unset template parameter: nodename
```

**Comment by WilliamMcCumstie** [comment]
So when I print the options hash that is inputted into the `BaseCommand`, it shows that the default template is not being passed in. However I can pass in other options (e.g. the teapot config).

```
bin/metal dhcp -c "I-am-a-little-teapot"
The option inputs are: <Commander::Command::Options config="I-am-a-little-teapot">
error: Error in MetalLog. Config not set. Use --trace to view backtrace
```

However when I display the help for `dhcp`, the default is being displayed. 
```
bin/metal dhcp -h
** STUFF **
  OPTIONS:
        
    -t TEMPLATE, --template TEMPLATE 
        Specify dhcp template to use
        Default: default
```
This indicates the default parameter is being passed in by the `CliHelper::Parser` but is not being returned by `Commander`.

The bug is likely in https://github.com/alces-software/commander

**Comment by WilliamMcCumstie** [comment]
This bug has been fixed in `Commander` (see link bellow). The bug fix is available in v2 of `metalware`
https://github.com/alces-software/commander/commit/d322ed15c6a12ede79e9bb8e9465738818efe0fc
